### ISSUE TITLE
[helm] bk-iam-search-engine

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#1721]
默认值 `redis.enabled = false` 会用户进到里面最小化安装无法部署起来

本意是, 希望这里配置redis同saas的redis一致

所以, 这里的默认值是否可以配置成bkiam-saas的redis地址?

```
  ## If the Redis(TM) included in the chart is disabled, Harbor will use below
  ## Redis(TM) parameters to connect to an external Redis(TM) server.
  ## Support for both Redis(TM) and Redis+Sentinel(TM)
  ##    
  externalRedis:
    default:
      ## Redis(TM) host
      ##
!     # redis://:bkiam@bkiam-saas-redis-master:6379/0
+     host: bkiam-saas-redis-master
      ## Redis(TM) port number
      ##
      port: 6379
      ## Redis(TM) password
      ##
!     password: "bkiam"                                                                                                                                               
      ## Redis(TM) db name
      ##
      db: 0 
```

然后, bkiam-search-engine 必须强依赖于bkiam-saas的部署
